version: '2'
services:
    manprod-app:
        image: manprod
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://manprod-postgresql:5432/ManProd
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    manprod-postgresql:
        extends:
            file: postgresql.yml
            service: manprod-postgresql
