version: '2'
services:
    manprod-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/ManProd/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=ManProd
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
